-- up
CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  google_sub VARCHAR(64) NULL UNIQUE,
  college_email VARCHAR(190) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  roll_no VARCHAR(20) NULL,
  batch_year SMALLINT NULL,
  branch VARCHAR(16) NULL,
  status ENUM('ACTIVE','PENDING','SUSPENDED','ALUMNI') NOT NULL DEFAULT 'ACTIVE',
  show_in_leaderboard TINYINT(1) NOT NULL DEFAULT 1,
  avatar_url VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_cohort (status, batch_year, branch),
  INDEX idx_users_name (display_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE roles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code ENUM('MEMBER','MENTOR','EDITOR','MODERATOR','ADMIN','SUPERADMIN') NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_roles (
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  granted_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO roles (code) VALUES
  ('MEMBER'),('MENTOR'),('EDITOR'),('MODERATOR'),('ADMIN'),('SUPERADMIN');

-- down
DROP TABLE user_roles;
DROP TABLE roles;
DROP TABLE users;
